baseURL = 'https://bongjunj.github.io/'
languageCode = 'ko'
languageName = 'Korean'
title = 'Bongjun Jang'
theme = 'blank'

[params.author]
name = "Bongjun Jang"
email = "bongjun.jang [at] kaist.ac.kr"
