baseURL = 'https://bongjunj.github.io/'
languageCode = 'ko'
languageName = 'Korean'
title = 'Bongjun Jang'
theme = 'blank'

[params.author]
name = "Bongjun Jang"
email = "bongjun.jang [at] kaist.ac.kr"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
[params]
math = true
