baseURL = 'https://bongjunjang.com/'
languageCode = 'ko'
languageName = 'Korean'
title = 'Bongjun Jang'
theme = 'LoveIt'

hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
name = "Bongjun Jang"
email = "bongjun.jang@kaist.ac.kr"

[menu]
[[menu.main]]
weight = 1
identifier = "posts"
pre = ""
post = ""
name = "Posts"
url = "/posts/"
title = "Posts"

[[menu.main]]
weight = 2
identifier = "projects"
name = "Projects"
url = "/projects/"
title = "Projects"

[[menu.main]]
weight = 3
identifier = "travels"
name = "Travels"
url = "/travels/"
title = "Travels"

[params]
# site default theme ["auto", "light", "dark"]
defaultTheme = "light"

# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/dillonzq/LoveIt"

# which hash function used for SRI, when empty, no SRI is used
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = "sha256"

# date format
dateFormat = "2006-01-02"

# website title for Open Graph and Twitter Cards
title = "Bongjun Jang"

# website description for RSS, SEO, Open Graph and Twitter Cards
description = "Bongjun Jang's personal blog"

# website images for Open Graph and Twitter Cards
images = ["/logo.png"]
[params.header]
# desktop header mode ["fixed", "normal", "auto"]
desktopMode = "fixed"
# mobile header mode ["fixed", "normal", "auto"]
mobileMode = "auto"
# Header title config
[params.header.title]
# URL of the LOGO
# LOGO 的 URL
logo = ""
# title name
name = "Bongjun Jang"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
# whether to use typeit animation for title name
typeit = false
[params.home]
# LoveIt NEW | 0.2.0 amount of RSS pages
rss = 10
# Home page profile
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = ""
# LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
title = "Student&lt;Computer Science&gt;"
# subtitle shown in home page (HTML format is supported)
subtitle = ""
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
disclaimer = ""
# Home page posts
[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 6
# LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
# default behavior when you don't set "hiddenFromHomePage" in front matter
defaultHiddenFromHomePage = false
